version: "2.13"

services:
  api:
    build: 
      dockerfile: Dockerfile
      context: /LinkediN-Clone
      target: development
      command: yarn start:dev
      environtment: 
        NODE_ENV: development
        PORT: 3000
        ports: 
        - 3000:3000
        - 9229:9229

